version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  cache:
    image: redis:7.2.3
    ports:
      - '6379:6379'

  migrate:
    image: migrate/migrate
    volumes:
        - ./migration:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

